### PR TITLE
Added support for lists in query2

### PR DESCRIPTION
**Pull request by johan-bjareholt**
- List support
- Misc query2 fixes
- changed 
- renamed limit_events(events, count) to first(events, count) and added last(event, count)

aw-webui needs these changes for compatibility https://github.com/ActivityWatch/aw-webui/pull/66

### CODE REVIEW

**Comment by ErikBjare** [comment]
I think `first` and `last` are bad names for the functions. Consider that `last(events, 50)` would be equivalent to `reversed(limit(reversed(events), 50)`.

**Comment by ErikBjare** [comment]
Also, weird that AppVeyor fails. But doesn't seem to be caused by your commits.

**Comment by johan-bjareholt** [comment]
> I think first and last are bad names for the functions. Consider that last(events, 50) would be equivalent to reversed(limit(reversed(events), 50)

limit is even more confusing IMO because it doesn't specify what it's actually limiting.
Adding a reverse function however would be very useful!

**Comment by ErikBjare** [comment]
Looks like me merging https://github.com/ActivityWatch/aw-core/pull/55 created some conflicts, could you look into fixing them @johan-bjareholt and I'll implement `reversed` and `limit` (where limit would take the n first) instead of `first` and `last`.

**Comment by johan-bjareholt** [comment]
> Looks like me merging #55 created some conflicts

"Some" conflicts was an understatement...

Seems to work now atleast, but each individual commit is likely broken now so probably better to just sqash it all before merge later.

**Comment by johan-bjareholt** [comment]
> I think first and last are bad names for the functions.

Reverted to previous limit_events

**Comment by johan-bjareholt** [comment]
> Just a question, why remove the spaces around the = assignments in the queries? I find it more difficult to read that way.

Mistake during the rebase, will fix

**Comment by johan-bjareholt** [comment]
> Looks good to me, if you can fix the weird limit bug in CI.

Fixed

**Comment by johan-bjareholt** [comment]
Improved coverage now a bit well too (99% on query2.py), merging

**Pull request merged**
