### PR TITLE
moved from Pipfile/setup.py/pipenv to pyproject.toml/poetry

### PR DESCRIPTION
**Pull request by ErikBjare**

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
You forgot to update the Makefiles!!!

**Comment by ErikBjare** [comment]
@johan-bjareholt Uh no? pip supports pyproject.toml for non-dev installation.

**Comment by johan-bjareholt** [comment]
@ErikBjare Oh, I was trying to install with DEV=1 and it didn't work so I assumed that it's broken.

So if i understand things corrently, now we lost support for --editable and "setup.py develop" so we're required to either install every time we change something or use an virtualenv?

**Comment by ErikBjare** [comment]
Huh, I didn't know that `--editable` had broken, I'll look into it.

`poetry install` will set up a virtualenv and install the package as editable.

**Comment by ErikBjare** [comment]
Alright, I should have fixed it in https://github.com/ActivityWatch/aw-core/commit/4f4b4b241d2d9873c85af81be30ad2770d0d1fc0. The solution was simply to opt for using `poetry install` over `pip3 install` when `DEV` is set.

Apparently `--editable` isn't supported by PEP0517 so pyproject.toml can't support it, but since `poetry install` does the equivalent by default we should simply opt for using it in case we're installing for development purposes.

**Comment by ErikBjare** [comment]
Working on fixing the other packages as well btw

**Pull request merged**
