### PR TITLE
query2: Add support for escaped strings

### PR DESCRIPTION
**Pull request by johan-bjareholt**
This + web-ui escaping should fix https://github.com/ActivityWatch/aw-webui/issues/133

### CODE REVIEW

**Comment by ErikBjare** [comment]
I'm not comfortable with the parser internals, but have you considered options like these?: https://stackoverflow.com/questions/1885181/how-do-i-un-escape-a-backslash-escaped-string-in-python

**Comment by johan-bjareholt** [comment]
@ErikBjare That's the opposite of what this PR achieves? This code doesn't un-escape, it makes it possible to escape.

**Comment by ErikBjare** [comment]
Ah, fair enough. I don't see any tests for strings like `'Hello "world"!'` though. Shouldn't there be?

**Comment by johan-bjareholt** [comment]
We should add that just to be sure of future changes not breaking it, but that's safe currently as it only matches the first quote type with another one of the same type.

**Comment by ErikBjare** [comment]
@johan-bjareholt Sorry, the first example I made wasn't what I really meant. Edited the comment.

**Comment by johan-bjareholt** [comment]
I realized that there was multiple faults with the previous code after writing some more tests, should be better now.

**Comment by johan-bjareholt** [comment]
Fixed yet another bug, I have now tested with creating buckets containing a ' with aw-fakedata and it works. Will also have to test with buckets containing a "

**Pull request merged**
