### PR TITLE
Event properties

### PR DESCRIPTION
**Pull request by ErikBjare**

### CODE REVIEW

**Comment by ErikBjare** [comment]
@johan-bjareholt Can I merge?

**Comment by johan-bjareholt** [comment]
Seems to work fine!

**Comment by johan-bjareholt** [comment]
The filter seems to crash when you insert a event without a duration as a filter event, how should this be handled?

**Comment by johan-bjareholt** [comment]
I might be wrong, but it seems like if you write "for label in event["label"]" it will choose labels[0] and interade over the characters which is pretty annoying.

**Comment by ErikBjare** [comment]
@johan-bjareholt I don't believe that is the case. `event["label"]` will always return a list. `event.label` however will return a string (or None).

**Comment by ErikBjare** [comment]
Merging now, I think we're done here

**Pull request merged**
